export enum ModalType {
    DetailOrder = 'DetailOrder',
    OrderHistory = 'OrderHistory',
    Checkout = 'Checkout',
    UpdatePassword = 'UpdatePassword',
    CreateUser = 'CreateUser',
    UpdateUser = 'UpdateUser',
    CreateBrand = 'CreateBrand',
    UpdateBrand = 'UpdateBrand',
    CreateColor = 'CreateColor',
    UpdateColor = 'UpdateColor',
    CreateSize = 'CreateSize',
    UpdateSize = 'UpdateSize',
    CreateDiscount = 'CreateDiscount',
    UpdateDiscount = 'UpdateDiscount',
    CreateCategory = 'CreateCategory',
    UpdateCategory = 'UpdateCategory',
    ProductImage = 'ProductImage',
    CreateProductItem = 'CreateProductItem',
    UpdateProductItem = 'UpdateProductItem',
    CreateVariation = 'CreateVariation',
    UpdateVariation = 'UpdateVariation',
    AddRating = 'AddRating',
    UpdateOrder = 'UpdateOrder',
}
