export enum ModalType {
    UpdatePassword = 'UpdatePassword',
    CreateUser = 'CreateUser',
    UpdateUser = 'UpdateUser',
    CreateProvince = 'CreateProvince',
    UpdateProvince = 'UpdateProvince',
    CreateSize = 'CreateSize',
    UpdateSize = 'UpdateSize',
    CreateCompany = 'CreateCompany',
    UpdateCompany = 'UpdateCompany',
    CreateCategory = 'CreateCategory',
    UpdateCategory = 'UpdateCategory',
    CreateTagname = 'CreateTagname',
    UpdateTagname = 'UpdateTagname',
}
