export enum ModalType {
    UpdatePassword = 'UpdatePassword',
    CreateUser = 'CreateUser',
    UpdateUser = 'UpdateUser',
    CreateProvince = 'CreateProvince',
    UpdateProvince = 'UpdateProvince',
    CreateSize = 'CreateSize',
    UpdateSize = 'UpdateSize',
    CreateCompany = 'CreateCompany',
    UpdateCompany = 'UpdateCompany',
    CreateCategory = 'CreateCategory',
    UpdateCategory = 'UpdateCategory',
    CreateTagname = 'CreateTagname',
    UpdateTagname = 'UpdateTagname',
    CreateWorkType = 'CreateWorkType',
    UpdateWorkType = 'UpdateWorkType',
    CreateExperience = 'CreateExperience',
    UpdateExperience = 'UpdateExperience',
    CreateGender = 'CreateGender',
    UpdateGender = 'UpdateGender',
    CreateRank = 'CreateRank',
    UpdateRank = 'UpdateRank',
    CreateJobCategory = 'CreateJobCategory',
    UpdateJobCategory = 'UpdateJobCategory',
}
